export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_BOOK_BEGIN = "CREATE_BOOK_BEGIN";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_ERROR = "CREATE_BOOK_ERROR";

export const GET_SELL_BEGIN = "GET_SELL_BEGIN";
export const GET_SELL_SUCCESS = "GET_SELL_SUCCESS";

export const GET_OWNED_BOOK_SUCCESS = "GET_OWNED_BOOK_SUCCESS";

export const SET_UPDATE_SELL = "SET_UPDATE_SELL";

export const UPDATE_BOOK_BEGIN = "UPDATE_BOOK_BEGIN";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_ERROR = "UPDATE_BOOK_ERROR";

export const DELETE_BOOK_BEGIN = "DELETE_BOOK_BEGIN";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_ERROR = "DELETE_BOOK_ERROR";

export const CHOOSE_BOOK = "CHOOSE_BOOK";

export const CREATE_WISH_BEGIN = "CREATE_WISH_BEGIN";
export const CREATE_WISH_SUCCESS = "CREATE_WISH_SUCCESS";
export const CREATE_WISH_ERROR = "CREATE_WISH_ERROR";

export const GET_WISHES_BEGIN = "GET_WISHES_BEGIN";
export const GET_WISHES_SUCCESS = "GET_WISHES_SUCCESS";

export const GET_OWNED_WISHES_SUCCESS = "GET_OWNED_WISHES_SUCCESS";

export const SET_UPDATE_WISH = "SET_UPDATE_WISH";

export const UPDATE_WISH_BEGIN = "UPDATE_WISH_BEGIN";
export const UPDATE_WISH_SUCCESS = "UPDATE_WISH_SUCCESS";
export const UPDATE_WISH_ERROR = "UPDATE_WISH_ERROR";

export const DELETE_WISH_BEGIN = "DELETE_WISH_BEGIN";
export const DELETE_WISH_SUCCESS = "DELETE_WISH_SUCCESS";
export const DELETE_WISH_ERROR = "DELETE_WISH_ERROR";

export const CHOOSE_WISH = "CHOOSE_WISH";