export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_SELL_BEGIN = "CREATE_SELL_BEGIN";
export const CREATE_SELL_SUCCESS = "CREATE_SELL_SUCCESS";
export const CREATE_SELL_ERROR = "CREATE_SELL_ERROR";

export const GET_SELL_BEGIN = "GET_SELL_BEGIN";
export const GET_SELL_SUCCESS = "GET_SELL_SUCCESS";

export const SET_UPDATE_SELL = 'SET_UPDATE_SELL';

export const UPDATE_SELL_BEGIN = "UPDATE_SELL_BEGIN";
export const UPDATE_SELL_SUCCESS = "UPDATE_SELL_SUCCESS";
export const UPDATE_SELL_ERROR = "UPDATE_SELL_ERROR";

export const DELETE_SELL_BEGIN = "DELETE_SELL_BEGIN";
export const DELETE_SELL_SUCCESS = "DELETE_SELL_SUCCESS";
export const DELETE_SELL_ERROR = "DELETE_SELL_ERROR";